export default {
    titolo: "Linux Lab",
    sottotitolo: "learning Linux with a real terminal",
    navIntro: "Basics",
    navQuaderno: "Notebook",
    navIndice: "Chapters",
    depthBase: "BASE",
    depthPro: "PRO",
    depthTitle: "PRO adds how it works underneath and what breaks",

    capPrec: "← Previous",
    capSucc: "Next →",
    capDi: "Chapter {0} of {1}",
    inLavorazione: "in progress",
    prerequisito: "This chapter assumes chapter {0}. If that means nothing to you, do it first.",
    vaiA: "go",

    labTitolo: "Lab",
    labScarico: "Downloading the machine… {0}%",
    labAvvio: "Booting Linux…",
    labPronta: "Machine ready",
    labErrore: "Image not built. See lab/README.md: <code>make -C lab all</code>",
    labReimposta: "Reset the machine",
    labReimpostaTitle: "Puts the machine back to its initial state. Use it without fear.",
    labRicomincia: "Restart the exercise",
    labNuovoMondo: "New world",
    labNuovoMondoTitle: "Same exercise, different numbers. It is the best revision there is.",
    labApri: "Open the terminal",
    labChiudi: "Close",

    tipoStato: "state",
    tipoRisposta: "answer",
    tipoMetodo: "method",
    esercizi: "Exercises",
    esercizio: "Exercise {0}",
    verifica: "Check",
    verificaInCorso: "Checking…",
    superato: "Passed",
    nonAncora: "Not yet",
    suggerimento: "Hint",
    suggerimentoAltro: "Another hint",
    soluzione: "Show the solution",
    cosaHaVisto: "What the machine saw",
    perche: "Why",
    provaQuesto: "Try looking at it this way",
    solPro: "PRO",
    checkPro: "required in PRO only",
    erroreVerifica: "The check did not answer. Try again, or reset the machine.",

    bloccoTrappole: "Where everybody slips",
    bloccoRecap: "Recap",
    bloccoPro: "Under the hood",
    recapComando: "Command",
    recapCosa: "What it is for",
    recapOpzione: "The option you will actually use",

    localeTitolo: "This chapter runs on your own computer",
    localeCopia: "Copy the command",
    localeCopiato: "Copied",
    predizione: "Before you look: what happens?",
    predizioneGiusta: "Exactly.",
    predizioneSbagliata: "Not quite.",
    mostraOutput: "Show what happened",
    passoSucc: "Next step →",

    quadernoTitolo: "Your notebook",
    quadernoVuoto: "Still empty. Every command you meet while solving an exercise ends up here.",
    quadernoEsporta: "Export to Markdown",
    quadernoDa: "from chapter {0}",

    chiudi: "Close",
    mobileAvviso: "The terminal needs a real keyboard: on a phone you can read everything, but come back from a computer to practise.",
    introTitolo: "From scratch",
    introInizia: "Got it — on to chapter 1 →",
};
